//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroTetris3
{
    
    internal class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("MicroTetris3.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Consolas23 = -31666,
            NinaB = 18060,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            LinesCompleted = -27201,
            HighScore = -22559,
            PressAnyKey = -21048,
            ExtremeLevel = -20249,
            Level = -13726,
            Score = -13075,
            AdvancedLevel = -11619,
            GameOver = -10866,
            PressSelect = -9962,
            UseArrows = -8823,
            RookieLevel = 9176,
            ViewHighScore = 13410,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            Logo = 16403,
        }
    }
}
